# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest # runnner
    steps:
    - name: fetch your code # task
      uses: actions/checkout@v4

    - name: login to docker hub #automated task
      run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}

    - name: build docker image
      run: docker build -t ${{secrets.DOCKER_USERNAME}}/awsdeployment .

    - name: push docker image
      run: docker push ${{secrets.DOCKER_USERNAME}}/awsdeployment:latest

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
    - name: pull docker image
      run: docker pull ${{secrets.DOCKER_USERNAME}}/awsdeployment:latest

    - name: stop old container
      run: docker stop awsdeployment || true

    - name: remove old container
      run: docker rm awsdeployment || true

    - name: run new container
      run: docker run -d -p 80:8060 --name awsdeployment ${{secrets.DOCKER_USERNAME}}/awsdeployment:latest


